apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
      - name: auth-service
        image: devops-auth-service
        imagePullPolicy: Never
        ports:
        - containerPort: 9092